### ISSUE TITLE
Suggestion: Enable Issues in other projects

### ISSUE THREAD

**Issue by lars18th** [Linaro1985/usefull_scripts#1]
Hi @Linaro1985 ,

This is an open message for you: Please, enable the "Issues" of other projects you have forked. For example, the LEDE project for Archer C20i (https://github.com/Linaro1985/lede-source).

I like to put some suggestions/questions to help in your project. However, without this it's impossible.

See here to know about how to enable it: https://softwareengineering.stackexchange.com/questions/179468/forking-a-repo-on-github-but-allowing-new-issues-on-the-fork
(`Options/Settings/Features --> Issues [enable it]`)

Regards!

**Comment by Linaro1985** [comment]
Hi @lars18th,
But it doesn't make sense. As this fork is used for my personal development and all changes in a result pass into an official repository of OpenWrt/Lede. I will remove this fork soon as soon as there is an official release of OpenWrt. OpenWrt will become a working fork. Also I want to notice that I didn't do anything for the TP-Link Archer C20i device.

**Comment by lars18th** [comment]
Hi @Linaro1985 ,

Thank you for comment! :smile: 

> Also I want to notice that I didn't do anything for the TP-Link Archer C20i device.

So, you aren't doing _testing_ with the Archer C20i? No are you _compiling_ OpenWRT for this device?

If so, I have two requests for your repo (this it's the reason for requesting the issue enable):

- Include the ".config" file in the repository. Without this file it's impossible to recompile using exactly the same configuration you do it (useful for compile modules).
- Compile also the "initramfs" release, instead of only the "sysupgrade" version (https://github.com/Linaro1985/lede-source/releases).
-- And why this? Because then we can boot the image for testing without flashing it (booting using the TFTP mode of the Bootloader).
-- To enable the "sysupgrade": When execute the "make menuconfig" then select "TARGET IMAGES" ---> and enable RAMDISK. Leave enabled "SQUASHFS" too. After compile in the "bin/ramips/" directory you will see the "*-squashfs-sysupgrade.bin" and the "*-initramfs-kernel.bin". The you can upload both files to the _release directory_ of the GitHub.

I hope you agree with these minimal changes.
Thank you!

**Comment by Linaro1985** [comment]
@lars18th 
> So, you aren't doing testing with the Archer C20i? No are you compiling OpenWRT for this device?
I support only TP-Link Archer C20 v1 or TP-Link Archer C20 v4.

Regards!

**Comment by lars18th** [comment]
> I support only TP-Link Archer C20 v1 and TP-Link Archer C20 v4.

OK. So, can you please do my suggestions in your repository?
Thank you in advance! :smile:

**Comment by Linaro1985** [comment]
Config is official: [config.seed](https://downloads.openwrt.org/releases/17.01.4/targets/ramips/mt7620/config.seed).

**Comment by lars18th** [comment]
Hi @Linaro1985 ,

> Config is official: config.seed

Thank you! So, please can you update the page of the "releases" to include the link of the "config.seed". It will be necessary for other users for re-compile and generate a the firmware.

And regarding the "initramfs" release: You agree to generate it too?

Regards!

**Comment by Linaro1985** [comment]
> the page of the "releases" to include the link of the "config.seed"
Why? Config is official. It can be downloaded without problems from the page of releases OpenWrt.
> And regarding the "initramfs" release: You agree to generate it too?
As I notes earlier - it doesn't make sense. The fork together with all releases will be removed soon. So I won't generate it. In addition the official OpenWrt release doesn't include "initramfs" image. People who can launch "initramfs" image can build it without any problems from the source code. Users need only ready binaries for installation on the device via tftp.

**Comment by lars18th** [comment]
Hi @Linaro1985 ,

> Why? Config is official. It can be downloaded without problems from the page of releases OpenWrt.

Why? If someone doesn't knows this, and likes to use your repo for recompile it.
And why not put a simple link in the page of releases?

> The fork together with all releases will be removed soon.

OK. But for other people that are in the road of supporting similar devices (same hardware) this repo it's useful. So I suggest to not remove it (just freeze)!

> In addition the official OpenWrt release doesn't include "initramfs" image.

I know. This is the question to request it!

> People who can launch "initramfs" image can build it without any problems from the source code. 

Not all the times! If the ".config" if missing, they can't do it. If some new branch is in testing, then some files can be missing... Futermore, the _official_ OpenWRT/LEDE documentation isn't just good about how to add support for new devices.
In my opinion, the "initranfs" should be part of the official images, but I'm not the person how decides this. The compilation of it can be done in parallel with the regular "squashfs" and it's just one line more in the config. So, the build time it's increased only a bit. However, the output size increases a double. This it's the only drawback.

> Users need only ready binaries for installation on the device via tftp.

"Regular" users: YES.
For users that have access to the Bootloader over the serial: NO. The "initramfs" version it's a must have for testing "unkown"/"new" devices.

In any case, thank you for your responses. 😄 
And for your good work!

**Comment by Linaro1985** [comment]
Hi, @lars18th 
> OK. But for other people that are in the road of supporting similar devices (same hardware) this repo it's useful. So I suggest to not remove it (just freeze)!

All my commits already in the official OpenWrt repo. For a example:
[ramips: add support for TP-Link Archer C20 v1](https://github.com/openwrt/openwrt/commit/161a3be5adb21135eb75da81247fa5e04b6ea676#diff-a8d92c893e7a0a3b15a35fe46916deae)
[ramips: add support for TP-Link Archer C20 v4](https://github.com/openwrt/openwrt/commit/5bdd238b634a34b038fbea9046893de29a77c000#diff-ae11abc43ee9dcc01a87a00ded28391e58)
[ramips: rename TP-Link Archer C20 to TP-Link Archer C20 v1](https://github.com/openwrt/openwrt/commit/ff1e89553078cb1f8851276537d1267930d740df#diff-2b78b1cbb6a656eadc96c778602928a9)
Whether it is simpler to use an official repository?

> Futermore, the official OpenWRT/LEDE documentation isn't just good about how to add support for new devices.

What about official commits in a OpenWrt repository? I used [documentation](https://openwrt.org/docs/guide-developer/adding_new_device), GPL Source code from TP-Link and them. Problems weren't.

**Comment by lars18th** [comment]
Hi @Linaro1985 ,

Thank you for all this useful information! :smile: 

In any case, if you can the next time compile also the "initramfs" image. It's simple and it will help others.

Regards!

**Comment by davidzmn** [comment]
> @lars18th
> 
> > So, you aren't doing testing with the Archer C20i? No are you compiling OpenWRT for this device?
> 
> I support only TP-Link Archer C20 v1 and TP-Link Archer C20 v4.
> 
> Regards!

Hi @Linaro1985 
I have Archer c20 V4 and would like to config 5GHz radio on OpenWrt 19.07-SNAPSHOT r10550-e9c16e4e1f / LuCI openwrt-19.07 branch (git-19.263.64892-befe994)
Already installed kmod-mt76x0e pakage ! everything is update but 5GHz radio doesn't show up there is only 2Ghz band 
what should I do?! 
I did read many tutorials but haven't helped me yet 
Can you please help me?! Thank you so much

**Comment by davidzmn** [comment]
> @lars18th
> 
> > So, you aren't doing testing with the Archer C20i? No are you compiling OpenWRT for this device?
> 
> I support only TP-Link Archer C20 v1 and TP-Link Archer C20 v4.
> 
> Regards!

Hi @Linaro1985
I have Archer c20 V4 and would like to config 5GHz radio on OpenWrt 19.07-SNAPSHOT r10550-e9c16e4e1f / LuCI openwrt-19.07 branch (git-19.263.64892-befe994)
Already installed kmod-mt76x0e pakage ! everything is update but 5GHz radio doesn't show up there is only 2Ghz band
what should I do?!
I did read many tutorials but haven't helped me yet
Can you please help me?! Thank you so much

**Comment by davidzmn** [comment]
Hi @Linaro1985
I have Archer c20 V4 and would like to config 5GHz radio on OpenWrt 19.07-SNAPSHOT r10550-e9c16e4e1f / LuCI openwrt-19.07 branch (git-19.263.64892-befe994)
Already installed kmod-mt76x0e pakage ! everything is update but 5GHz radio doesn't show up there is only 2Ghz band
what should I do?!
I did read many tutorials but haven't helped me yet
Can you please help me?! Thank you so much
